development:
  adapter: postgresql
  encoding: unicode
  database: NewSkin-development
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: NewSkin-test
  pool: 5
  port: 5432